import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/custom-ui/navbar";
import { RepoProvider } from "@/components/context/RepositoryContext";

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceMono.className}  antialiased`}>
        <RepoProvider>
          <div className="flex flex-col items-center w-full">
            <Navbar />
            {children}
          </div>
        </RepoProvider>
      </body>
    </html>
  );
}
